name: Deploy Prod
on:
  push:
    branches: [release]
  workflow_dispatch:
jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Build
        run: |
          npm install
          npm run build

      - name: Publish
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: ${{ secrets.SSH_SERVER }}
          remote-user: ${{ secrets.SSH_USER }}
          private-ssh-key: ${{ secrets.SSH_KEY }}
          source-path: ./dist/
          destination-path: /home/zeldadungeon/public_html/maps/
          rsync-options: --recursive --compress --human-readable --progress --delete-after
